apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argo-cd
  name: main
  labels:
    app.kubernetes.io/part-of: main
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - name: infra-management
          group: infrastructure
          component: management
        - name: infra-operations
          group: infrastructure
          component: operations
        - name: dev-management
          group: development
          component: operations
        - name: dev-operations
          group: development
          component: operations
  template:
    metadata:
      name: '{{ .name }}'
      namespace: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: default:argoproj.io/Application:argo-cd/{{ .name }}
      labels:
        app.kubernetes.io/component: '{{ .component }}'
        app.kubernetes.io/part-of: '{{ .group }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Kube-Mind/demo-repository.git
        targetRevision: main
        path: 'k8s/{{ .group }}/{{ .component }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .group }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true