apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argo-cd
  name: main
  labels:
    app.kubernetes.io/part-of: main
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  generators:
    - git:
        repoURL: https://github.com/Kube-Mind/demo-repository.git
        revision: main
        directories:
          - path: k8s/*
  template:
    metadata:
      name: '{{ path.basename }}'
      namespace: argo-cd
      labels:
        app.kubernetes.io/component: '{{ path.basename }}'
        app.kubernetes.io/part-of: main
    spec:
      project: default
      source:
        repoURL: https://github.com/Kube-Mind/demo-repository.git
        targetRevision: main
        path: '{{ path }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ path.basename }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true