apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-management
  namespace: argo-cd
  labels:
    app.kubernetes.io/component: management
    app.kubernetes.io/part-of: development
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/tracking-id: development:argoproj.io/Application:argo-cd/{{ path.basename }}
spec:
  description: Project for core development management
  sourceRepos:
    - 'https://github.com/Kube-Mind/demo-repository.git'
  destinations:
    - namespace: 'argo-cd'
      server: '*'
    - namespace: 'external-secrets'
      server: '*'
    - namespace: 'system-upgrade'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'