apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argo-cd
  labels:
    app.kubernetes.io/instance: infrastructure
    app.kubernetes.io/part-of: main
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/tracking-id: infrastructure:argoproj.io/Application:argo-cd/{{ path.basename }}
spec:
  description: Infrastructure components managed through GitOps (all resources allowed)
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: admin
      description: Full permissions
      policies:
        - p, proj:infrastructure:admin, applications, *, *, allow
    - name: readonly
      description: Read-only access
      policies:
        - p, proj:infrastructure:readonly, applications, get, *, allow
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications:
        - '*'
      manualSync: true
  orphanedResources:
    warn: true