apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-operations
  namespace: argo-cd
  labels:
    app.kubernetes.io/instance: 'infra-operations'
    app.kubernetes.io/component: operations
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Project for core infrastructure operations
  sourceRepos:
    - 'https://github.com/Kube-Mind/demo-repository.git'
  destinations:
    - namespace: 'system-upgrade'
      server: '*'
    - namespace: 'system-upgrade-plans'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'