apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Project for core infrastructure controllers
  sourceRepos:
    - 'https://github.com/Kube-Mind/demo-repository.git'
  destinations:
    - namespace: 'argo-cd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'